version: '3'
services:
  redis:
    image: 'redis:latest'
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./backend:/app
