version: '3'
services:
  redis:
    image: 'redis:latest'
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '0.75'
    restart: always
